- id: 1
  code: mufg
  currency: jpy
  deposit: true
  withdraw: true
- id: 2
  code: smbc
  currency: jpy
  deposit: true
  withdraw: true
- id: 3
  code: mzh
  currency: jpy
  deposit: true
  withdraw: true
- id: 4
  code: nmrt
  currency: jpy
  deposit: true
  withdraw: true
- id: 5
  code: jpp
  currency: jpy
  deposit: true
  withdraw: true